# Data Pre-Processing

**Import Packages and CSV**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None) # None: display all columns, 100: display 100 columns, etc.

df = pd.read_csv("D:\\2025\\MLOPS-Project-US-Visa\\notebook\\EasyVisa.csv")
print(df.shape)

(25480, 12)

## 1. Data Cleaning

* Handling missing value
* Handling duplicate
* Check data type
* Understand the dataset

**Handling missing value**

In [2]:
feature_with_na = [feature for feature in df.columns if df[feature].isnull().sum() >= 1]

for feature in feature_with_na:
    print(feature, np.round(df[feature].isnull().mean()*100, 5), '% missing values')

In [3]:
feature_with_na

[]

**Report**
* No null value in the dataset

**Handling duplicate value**

In [4]:
print(df.duplicated().sum())

0

**Report**
* No duplicate in the dataset

** Remove case_id from the dataset as it cannot used in Model Training**

In [5]:
df.drop('case_id', axis=1, inplace=True) # axis=1: columns, axis=0: rows, inplace=True: modify the original dataframe, inplace=False: return a new dataframe

# 2. Feature Engineering

## 2.1 Feature Extraction

In [6]:
df.head()

,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [ ]:
from datetime import date
today_date = date.today() # date.today() returns the current local date as a datetime.date object.
current_year = today_date.year
current_year

2026

**Subtract current_year with yr_of_estab to get company's age**

In [12]:
df['company_age'] = current_year - df['yr_of_estab']
df.head()

,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status,company_age
0,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied,19
1,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified,24
2,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied,18
3,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied,129
4,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified,21

### Type of feature

**Categorical Features**

In [13]:
cat_features = [feature for feature in df.columns if df[feature].dtype == 'O']
print('Num of Categorical Features :', len(cat_features))

Num of Categorical Features : 8

**Numeric Features**

In [14]:
num_features = [feature for feature in df.columns if df[feature].dtype != 'O']
print('Num of Numerical Features :', len(num_features))

Num of Numerical Features : 4

**Discrete features**

In [15]:
discrete_features=[feature for feature in num_features if len(df[feature].unique())<=25]
print('Num of Discrete Features :',len(discrete_features))

Num of Discrete Features : 0

**Continues Features**

In [16]:
continuous_features=[feature for feature in num_features if feature not in discrete_features]
print('Num of Continuous Features :',len(continuous_features))

Num of Continuous Features : 4